### ISSUE TITLE
UnauthorizedAccessException On Launch

### ISSUE THREAD

**Issue by PhantomGamers** [U-1F31A/BepInEx_Valheim_Full_Updater#1]
When I launch the game with this mod active in r2modman I get the following error. I imagine this must be something wrong on my end, though I get the error even when running the game exe as admin (though of course I normally do not run it as admin, and the error occurs then as well, on both the client and the server.)
`[Error  : Unity Log] UnauthorizedAccessException: Access to the path "%localappdata%\Temp\1F31A-BepInEx_Valheim_Full-1.0.2.zip" is denied.
Stack trace:
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean isAsync, System.Boolean anonymous) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess)
System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) (at <ef151b6abb5d474cb2c1cb8906a8b5a4>:0)
Rethrow as WebException: An exception occurred during a WebClient request.
System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) (at <ef151b6abb5d474cb2c1cb8906a8b5a4>:0)
System.Net.WebClient.DownloadFile (System.String address, System.String fileName) (at <ef151b6abb5d474cb2c1cb8906a8b5a4>:0)
(wrapper remoting-invoke-with-check) System.Net.WebClient.DownloadFile(string,string)
BepInEx_Valheim_Full_Updater.BepInExValheimFullUpdater.Download (System.String downloadUrl, System.String outPath) (at <cb8fedb434884d6f9608017e9c8fa542>:0)
BepInEx_Valheim_Full_Updater.BepInExValheimFullUpdater.Install (System.String installDir, System.Boolean isLinuxServer) (at <cb8fedb434884d6f9608017e9c8fa542>:0)
BepInEx_Valheim_Full_Updater.BepInExValheimFullUpdater.Awake () (at <cb8fedb434884d6f9608017e9c8fa542>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()`

**Comment by PhantomGamers** [comment]
This is definitely just an issue on my end, apparently after switching out my cpu and motherboard my file permissions got all wonky.

**Comment by sebastienvercammen** [comment]
A self-resolving issue for my first issue submission, I'm honored. :heart:

Thanks for the report, and thanks for solving it! If anything else happens, don't hesitate to let me know again.
